### PR TITLE
Fill changelog for 0.0.21 release

### PR DESCRIPTION
**Pull request by and-semakin**
## What do these changes do?

This PR tries to summarize changes that happened after the 0.0.20 release.
See this message for additional context: https://github.com/aio-libs/aiomysql/issues/466#issuecomment-668589737

## Are there changes in behavior for the user?

No.

## Related issue number

#466

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by and-semakin** [comment]
Oh, what's wrong with codecov? Does it count coverage of the CHANGELOG?

**Comment by jettify** [comment]
I will take a look over thanksgiving weekend (hopefully tomorrow).

**Review by jettify — APPROVED** [review]

**Comment by jettify** [comment]
New version on PyPI https://pypi.org/project/aiomysql/0.0.21/

**Comment by and-semakin** [comment]
Thank you so much @jettify! You made my day ❤️

**Pull request merged**
