### PR TITLE
fix issued with cancelled transaction

### PR DESCRIPTION
**Pull request by jettify**
Issues reported in: https://groups.google.com/forum/#!topic/aio-libs/0uaOA_pHtYo

### CODE REVIEW

**Comment by Drizzt1991** [comment]
I think the test for the test scenario is wrong. You sure may receive a CancelError on the begin/commit/rollback, but as I read the post on google group it should be something like:

```Python
with (yield from mysql_pool) as conn:
    yield from conn.begin()
    # Do something between
    try:
        yield from sleep(1)  # <- Cancellation will be here I think
    except:
        yield from conn.rollback()
        raise
    else:
        yield from conn.commit()
```

**Comment by Drizzt1991** [comment]
The problem is that if we cancel the coroutine between begin and commit/rollback (transaction is in process) the connection should not be just returned to pool, but either rollback'ed or just closed.

**Comment by jettify** [comment]
Pool is smart, it drops connection that in transaction mode:
https://github.com/aio-libs/aiomysql/blob/master/aiomysql/pool.py#L202-L206

**Comment by terrycain** [comment]
@jettify This still needed? As i'll fix the conflicts if so

**Comment by sconeyard** [comment]
@terrycain This seems to be the fix for #195. As such it still seems to be relevant.

**Comment by terrycain** [comment]
@jettify fix conflicts, flake and deprecation warning on `asyncio.async`, looks good, but a second opinion would be great.

**Comment by jettify** [comment]
Thanks! Will review this weekend

**Pull request closed without merging**
