### PR TITLE
add mariadb addon to suite of builds

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by asvetlov** [comment]
As far as I see the PR replaces standard MySQL with MariaDB.
MariaDB support worth to be tested but I prefer keeping MySQL DB also.

**Comment by grooverdan** [comment]
it doesn't https://travis-ci.org/grooverdan/aiomysql

**Comment by jettify** [comment]
Looks like ``matrix.include`` used to add test cases to existing matrix: 
http://docs.travis-ci.com/user/customizing-the-build/#Explicity-Including-Builds

LGTM

**Comment by jettify** [comment]
Thanks!

**Pull request merged**
