### PR TITLE
make pool.release return future

### PR DESCRIPTION
**Pull request by jettify**

### CODE REVIEW

**Comment by asvetlov** [comment]
LGTM

**Comment by methane** [comment]
What is motivation to wait releasing connection?

**Comment by jettify** [comment]
Main reason, just to make sure we do not leave opened connections in background task, and all exception that happened there are raised in proper coroutine, otherwise in best case we will see exception in logs.

**Comment by methane** [comment]
Thanks for reply.  I got it.

By the way, "This is **NOT** a coroutine." in docstring of `release` is misleading, since it returns  awaitable now.

**Comment by jettify** [comment]
Thanks for pointing. Yes, unfortunately documentation is outdated, updating is what I going to work on next. My plan is to move all examples and docs to python3.5 syntax and add section on new apis. Then work on PyMySQL 0.7 compatibility.

**Pull request merged**
