### PR TITLE
Added sequence checks for packets.

### PR DESCRIPTION
**Pull request by Drizzt1991**
Synced changes in PyMySQL for sequence checking. What do we do about the tests for this? I kinda can't get how to test it.

### CODE REVIEW

**Comment by jettify** [comment]
Good question, I think we just need to make sure that those code actually get hit all tests are passed...

**Comment by Drizzt1991** [comment]
Well all tests passed, no need to fix anything. What kinda worries me is this section
https://coveralls.io/builds/5215319/source?filename=aiomysql%2Fconnection.py#L592
Was it never covered by tests?

**Comment by Drizzt1991** [comment]
I think it's OK to merge this. The part was not covered before. We can do it in a separate PR.

**Comment by jettify** [comment]
Looks good! Do you need release on pypi?

**Comment by Drizzt1991** [comment]
Would be great!

**Pull request merged**
