### PR TITLE
"Echo" was not passed to cursor

### PR DESCRIPTION
**Pull request by Reonaydo**

### CODE REVIEW

**Comment by jettify** [comment]
Please fix flake8 error (line length).

**Comment by jettify** [comment]
Please add test case
(related issue https://github.com/aio-libs/aiomysql/issues/63 )

**Comment by Reonaydo** [comment]
Sorry but I don`t understand what I need to do. How/Where can I add test case ?

**Comment by jettify** [comment]
Sorry for delay, simple dummy test is what have be done 👍

**Comment by jettify** [comment]
Thanks!

**Pull request merged**
