### PR TITLE
SSL Support (plus mysql_clear_password plugin for RDS)

### PR DESCRIPTION
**Pull request by terrycain**
Git closed last one when i force pushed.

Long discussion in #225

@jettify @terrisgit - new PR, less code :D

Also credit to Alex as I made a test where MySQL then tried to renegotiate the auth plugin, so I imported his `process_auth` function (and github realises it was him :smile:)

@jettify whats next.

### CODE REVIEW

**Comment by terrycain** [comment]
It passes travis, merge merge merge!!! :D

**Comment by jettify** [comment]
I will try to review tonight, have lots of thing to do this days after work.

**Comment by jettify** [comment]
@terrycain you did very good job! PR concise and elegant!

**Comment by terrycain** [comment]
@jettify No problem, was easy after learning that trick with passing in an active socket to open_connection.

Will pr again in a bit to add SSL example + an example of how to use it with RDS's token thing.

Onto other things, mind checking out my aiobotocore pr :wink:

**Comment by terrisgit** [comment]
I'll be user #2 !

**Comment by terrycain** [comment]
@terrisgit It probably already does, raise some issues and I'll get cracking

**Comment by terrycain** [comment]
Hmm not good, if you can find some repeatable code that will trigger it I'll get on that this weekend

**Comment by terrisgit** [comment]
False alarm. I was also testing with PyMySQL's master which seems to be unstable. :(

**Comment by jettify** [comment]
Can you share traceback?

**Comment by terrisgit** [comment]
There's definitely something wrong with 0.0.13 and the connection pool. My app is running about 5 queries at the same time through different connections all using the same pool. And all that code is looping. So not only are there 5 connections in the pool, these connections are running multiple queries sequentially. I am using pymysql 0.8.0, but I am confused whether aiohttp actually uses pymysql.

Obviously the same code runs as-is with terrycain's SSL implementation in #225. Only difference is when I swap in aiohttp 0.0.13.

I can successfully make one database connection via the pool. It's the looping highly async code that is failing.

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
BlockingIOError: [Errno 36] Operation now in progress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/aiomysql/connection.py", line 471, in _connect
    loop=self._loop)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 81, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 765, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 449, in sock_connect
    self._sock_connect(fut, sock, address)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 463, in _sock_connect
    self.add_writer(fd, self._sock_connect_cb, fut, sock, address)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 346, in add_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 258, in _ensure_fd_no_transport
    fd, transport))
RuntimeError: File descriptor 9 is used by transport <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/backoff/_async.py", line 132, in retry
    ret = yield from target(*args, **kwargs)
  File "/Users/terris/science37/edc-export-service/edcexport/model/dbexecutor.py", line 174, in execute_limit_update
    return await cls.execute_limit_update_once(query, query_args)
  File "/Users/terris/science37/edc-export-service/edcexport/model/dbexecutor.py", line 183, in execute_limit_update_once
    async with pool.acquire() as conn:
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/aiomysql/utils.py", line 146, in __aenter__
    self._conn = yield from self._coro
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/aiomysql/pool.py", line 139, in _acquire
    yield from self._fill_free_pool(True)
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/aiomysql/pool.py", line 186, in _fill_free_pool
    **self._conn_kwargs)
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/aiomysql/utils.py", line 70, in __iter__
    resp = yield from self._coro
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/aiomysql/connection.py", line 79, in _connect
    yield from conn._connect()
  File "/Users/terris/venv/edc/lib/python3.6/site-packages/aiomysql/connection.py", line 502, in _connect
    self._host) from e
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'db-nora-test-01.cti10lnrh4rb.us-west-2.rds.amazonaws.com'")

**Comment by terrisgit** [comment]
Let me keep trying some ideas out on my end..

**Comment by terrisgit** [comment]
My app is controlled by aiohttp which is stopped via control-c. Control-c is breaking active connections to the database - it sounds like https://github.com/aaugustin/websockets/issues/84 . Why this happens in #280 and not #225 is unknown.

**Comment by terrisgit** [comment]
It's going to take a long time to make a small program. I have some urgent unrelated bugs with my project that uses #225 and will get back to this afterward - probably 2 weeks.

**Comment by terrycain** [comment]
ahh so its fine until you try and kill a connection?

**Comment by terrisgit** [comment]
It has something to do with control-c (SIGINT) and specifically SSL. I am using aiohttp which establishes its own SIGINT handler, calls my start handler, and calls my stop handler when it gets SIGINT. See https://github.com/aaugustin/websockets/issues/84.

**Comment by terrycain** [comment]
Ok, i'll spin up something to see if i can reproduce

**Comment by terrycain** [comment]
Ok very weird, if I run the following in debug mode under pycharm, it works fine 100% of the time.
If I run it in pycharm without debugging I have less than a 1% success rate.

@jettify @terrisgit Any ideas why it would work whilst debugging and not when running normally?

```python
import asyncio
import ssl

import aiomysql


async def main(loop):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    ctx.check_hostname = False
    ctx.load_verify_locations(cafile='../tests/ssl_resources/ssl/ca.pem')

    print('pre_pool')
    pool = await aiomysql.create_pool(
        host='localhost',
        port=3308,
        user='root',
        password='root',
        loop=loop, ssl=ctx
    )

    print('start')
    await tls_query(pool)
    print('end')


async def tls_query(pool):
    async with pool.get() as conn:
        async with conn.cursor() as cur:
            # Run simple command
            await cur.execute("SHOW DATABASES;")
            value = await cur.fetchall()

            print(value)

            # Check TLS variables
            await cur.execute("SHOW STATUS LIKE '%Ssl_version%';")
            value = await cur.fetchone()
            print(value[1])


event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(main(event_loop))
```
Traceback:
```
Traceback (most recent call last):
  File "/home/terry/VCS/aiomysql/examples/example_ssl.py", line 42, in <module>
    event_loop.run_until_complete(main(event_loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f66bf7f21d0>
transport: <_SelectorSocketTransport fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f66bf7f21d0>
transport: <_SelectorSocketTransport closing fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 632, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 704, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 589, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 601, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by terrisgit** [comment]
OSError: [Errno 9] Bad file descriptor - yep, that's what I'm seeing too. I'm just running as "python3" which is 3.6.5 on OSX.

**Comment by terrisgit** [comment]
I use pool.acquire() .. probably doesn't make a difference .. should I be using pool.get() instead?

**Comment by terrisgit** [comment]
BTW, I'm trying your script right now.

**Comment by terrisgit** [comment]
Your script behaves fine for me. When my app exits, it makes sure that every asyncio task has finished and then it calls close() on the connection pool. I have problems whether I do this or not. When I call close() on the connection pool I get something like this which doesn't happen with #225.

[2018-04-21 16:11:25 asyncio ERROR] Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1051be0f0>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
[2018-04-21 16:11:25 asyncio ERROR] Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1051be898>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
[2018-04-21 16:11:25 asyncio ERROR] Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1051beef0>
transport: <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
[2018-04-21 16:11:25 asyncio ERROR] Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1051e1390>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

**Comment by terrisgit** [comment]
Control-C was a red herring. The problem is related to closing a connection pool when a connection is in use. #225 handles this gracefully; #280 does not.

```
from random import randint

import asyncio
import ssl

import aiomysql

async def main(loop):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    ctx.check_hostname = False
    ctx.load_verify_locations(cafile='../tests/ssl_resources/ssl/ca.pem')

    pool = None
    counter = 0

    while True:
        if not pool:
            pool = await aiomysql.create_pool(
                ...
                loop=loop, ssl=ctx
            )

        asyncio.ensure_future(tls_query(pool))

        counter += 1
        if (counter > (randint(0, 10)+1)):
            print("Closing pool")
            pool.close()
            pool = None

        if not (counter % 10):
            await asyncio.sleep(5)


async def tls_query(pool):
    try:
        async with pool.get() as conn:
            async with conn.cursor() as cur:
                # Run simple command
                await cur.execute("select sleep(rand()*1)")
                value = await cur.fetchall()
                print(value)
    except Exception as error:
        print(f"Failed {error}")  # Unable to print the exception message - if you try,
                         # "Exception Cannot acquire connection after closing pool"


event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(main(event_loop))
```

**Comment by terrisgit** [comment]
Unless you have found something weird with Python 3.5 (I use Python 3.6) I think my code is at fault. I don't exactly know where but it's clear that I need to deal the pool differently. Because the token is stored in the password field which is (I think) immutable, I create a new pool upon failure. Perhaps I should look into changing the password instead either by doing something bad or submitting a feature request.

**Comment by terrisgit** [comment]
This hangs in #280 but not in #225 . Sorry it's not minimal but I'm sure you can poke at it and find a simpler version.
```
from random import randint

import asyncio
import ssl

import aiomysql


async def main(loop):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    ctx.check_hostname = False
    # ctx.load_verify_locations(cafile=' .. ')

    pool = None
    counter = 0

    while True:
        if not pool:
            pool = await aiomysql.create_pool(
                host=' ',
                port=33XX,
                user=' ',
                password=' ',
                loop=loop, ssl=ctx
            )

        asyncio.ensure_future(tls_query(counter, pool))

        counter += 1

        if not counter % randint(1, 4):
            print("Closing the pool")
            pool.close()
            await pool.wait_closed()
            pool = None

            if counter > 30:
                break
        elif not counter % 5:
            await asyncio.sleep(randint(0, 5))
        else:
            await asyncio.sleep(0)


async def tls_query(counter, pool):
    print(f"Running query {counter}")
    try:
        async with pool.get() as conn:
            async with conn.cursor() as cur:
                await cur.execute("select 1")
                value = await cur.fetchall()
                print(f"{counter} - {value}")
    except Exception as error:
        print(f"Failed {counter} {error}")  # Cannot acquire connection after closing pool


event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(main(event_loop))
pending = asyncio.Task.all_tasks()
event_loop.run_until_complete(asyncio.gather(*pending))

print("Exiting")
```

**Comment by jettify** [comment]
Can you pleas check this patch? https://github.com/aio-libs/aiomysql/pull/282

**Comment by terrycain** [comment]
@jettify That patch looks like it did the tricl :smile:

@terrisgit Looks like the patch #282 seems to fix your example, I dont see any bad descriptor exceptions
I do see some `Failed 27 Cannot acquire connection after closing pool` but that is expected.

**Comment by terrisgit** [comment]
Yes, that fixed it! Hope you release it soon.

**Pull request merged**
