### PR TITLE
Issue #265 - _process_auth implementation

### PR DESCRIPTION
**Pull request by AlexLisovoy**

### CODE REVIEW

**Comment by jettify** [comment]
Looks good, but we need test case...

**Comment by jettify** [comment]
Do you know how to setup mysql server to support that auth? We can build docker image and test agains it.

**Comment by AlexLisovoy** [comment]
I'm working on test cases. During next week I will update this pr. My mysql version is 5.7.20, but I think it can be easeally reproduced on lower mysql version, because MySQL announce the AuthSwitch packet which contains two component `auth_plugin_name` and `auth_data` in version 5.5.

**Comment by AlexLisovoy** [comment]
@jettify I added test that can easily reproduce the issue locally with docker

**Comment by jettify** [comment]
Thanks a lot!

**Pull request closed without merging**
