### PR TITLE
dupclicate socket

### PR DESCRIPTION
**Pull request by jettify**

### CODE REVIEW

**Comment by terrycain** [comment]
Damn, this fixed my issue when it worked during debugging and not during running it normally, at least it looks like it did :D. 

Am interested to know how you thought of that? Down to experience, a google or was some logic applied?

**Comment by jettify** [comment]
Remembered that aiohttp did something like that, then found relevant code:
https://github.com/aio-libs/aiohttp/blob/a7bbaadd5e4d7eccafabd3221d1240a9aedf24d8/aiohttp/connector.py#L914-L919

**Comment by terrisgit** [comment]
This resolves the control-C weirdness I experienced with #280. I will be using this in pre-production tomorrow. Thank you.

**Comment by jettify** [comment]
New version available on PyPI https://pypi.org/project/aiomysql/0.0.14/

**Pull request merged**
