### PR TITLE
Throw an exception when incompatible curos class is passed to SA engine

### LINKED ISSUE #263: DictCursor cursorclass breaks sqlalchemy engine fetching
Python 3.5, running on Linux, aiomysql 0.0.12

It can definitely be criticized, that I even tried to pass DictCursor into create_engine as a cursorclass, but I believe that the library should either ignore the cursor choice, or not accept the kwarg at all and thrown an exception, since it relies on the classic one. If it can work other cursor classes, It should at least check if they are compatible (or blacklist uncompatible ones)?

```
...
    /usr/local/lib/python3.5/dist-packages/aiomysql/sa/result.py", line 88, in as_tuple
    return tuple(self[k] for k in self)
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/sa/result.py", line 88, in <genexpr>
    return tuple(self[k] for k in self)
  File "/usr/local/lib/python3.5/dist-packages/aiomysql/sa/result.py", line 63, in __getitem__
    return self._row[index]
    KeyError: 0
```

### PR DESCRIPTION
**Pull request by iScrE4m**
Fixes #263 

Sorry for the delay :)

### CODE REVIEW

**Comment by terrycain** [comment]
@iScrE4m - `aiomysql/sa/engine.py:35:80: E501 line too long (83 > 79 characters)`
If you run `make flake` that'll reproduce the same issue. Tests wont run until flake8 is happy.

**Comment by iScrE4m** [comment]
I totally missed the CI! Although the 79 character limit is a a bit surprising. 

Sorry for the delayed fix, all tests seem to be passing now.

**Comment by terrycain** [comment]
Yeah I normally have the opinion of, we normally have widescreen monitors now, 150 will do, but in the spirit of PEP8, 79 it is :smile: 

Purely for some code coverage stats, I'd throw a test in [here](https://github.com/aio-libs/aiomysql/blob/master/tests/sa/test_sa_engine.py) to cause it to raise an exception, and ensure its raised. But then again its a simple change so thats up to @jettify :D

**Comment by jettify** [comment]
Thanks! I will add test case, should not be hard.

**Comment by jettify** [comment]
added test case here https://github.com/aio-libs/aiomysql/commit/fcde0a484f012cad2e31aac7b66b80bbb44a0207

**Pull request merged**
